# kkiller の code の条件に近づけた

globals:
  seed: 107
  device: cuda
  max_epoch: 10
  patience: 5
  use_amp: False
  val_fold: 0
  debug: false
  folds: [0, 1, 2, 3, 4]
  fold_size: 1

dataset:
  name: BirdCLEFDataset
  train: {}
  valid: {}

loader:
  train: {batch_size: 32, shuffle: True, num_workers: 2, pin_memory: True, drop_last: True}
  valid: {batch_size: 16, shuffle: False, num_workers: 2, pin_memory: True, drop_last: False}

accumulation: 2

model:
  name: Resnet1
  params:
    base_name: resnext50_32x4d
    pretrained: true
    classes: 397

optimizer:
    name: Adam
    params:
      lr:  8.0e-04

scheduler:
  name: CosineAnnealingLR
  params:
    eta_min: 1.0e-05
    T_max: 10
loss:
  name: BCEWithLogitsLoss
  params: {}

early_stopping:
  params: {mode: min, patience: 10}
