
globals:
  seed: 107
  device: cuda
  max_epoch: 20
  patience: 5
  use_amp: False
  val_fold: 0
  debug: False
  folds: [0, 1, 2, 3, 4]
  fold_size: 1

augmentation:
  FreqMask:
    mask_size: 10
    mask_num: 3
  TimeMask:
    mask_size: 10
    mask_num: 6

dataset:
  name: BirdClefDatasetnp
  train:
    distort: true
    max_read_sample: 6
  valid: {}

resample2:
  down_sample: 250
  up_sample_rate: 3

loader:
  train: {batch_size: 32, shuffle: True, num_workers: 2, pin_memory: True, drop_last: True}
  valid: {batch_size: 16, shuffle: False, num_workers: 2, pin_memory: True, drop_last: False}

MixUp:
  alpha: 1.0
  r: 0.5

accumulation: 2

model:
  name: Resnet1
  params:
    base_name: resnext50_32x4d
    pretrained: true
    classes: 397

optimizer:
    name: Adam
    params:
      lr: 1.0e-03

scheduler:
  name: CosineAnnealingLR
  params:
    eta_min: 1.0e-05
    T_max: 10
loss:
  name: BCEWithLogitsLoss
  params:

early_stopping:
  params: {mode: min, patience: 5}
